trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    workingDirectory: Indexer
    command: 'build'
    feedsToUse: 'select'
    versioningScheme: 'off'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    arguments: '-c Release --framework netcoreapp2.2 --runtime win10-x64'
    feedsToUse: 'select'
    versioningScheme: 'byBuildNumber'
    workingDirectory: 'Indexer'
    zipAfterPublish: false

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop'
    targetPath: 'Indexer'
